apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nextportfolio
  annotations:
    github.com/project-slug: frankmeszaros/nextportfolio
spec:
  type: other
  lifecycle: unknown
  owner: team-c
